persistence true
persistence_location /home/alfin/devplace/smartHL/mosquitto/data/
log_dest file /home/alfin/devplace/smartHL/mosquitto/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true

# MQTT native (ESP32, backend bridge)
listener 1883 0.0.0.0
protocol mqtt
allow_anonymous true

# WebSocket (dashboard web mqtt.js)
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true

# --- PROD: ganti ke mode auth ---
# allow_anonymous false
# password_file /home/alfin/devplace/smartHL/mosquitto/passwd
# acl_file /home/alfin/devplace/smartHL/mosquitto/acl
